SELECT
    FEATURE_ID,
    SNAPSHOT_DATE,
    PROGRAM_INCREMENT,
    SUM(STORY_POINTS) AS TOTAL_ESTIMATE,
    SUM(CASE WHEN STATUS = 'Done' THEN STORY_POINTS ELSE 0 END) AS DONE_ESTIMATE,
    SUM(STORY_POINTS)
    - SUM(CASE WHEN STATUS = 'Done' THEN STORY_POINTS ELSE 0 END)
    AS OPEN_ESTIMATE,
    COUNT(*) AS SPRINT_COUNT,
    MIN(BEGIN_DATE) AS BEGIN_DATE,
    MAX(END_DATE) AS END_DATE
FROM AMMM_JIRA_AGILE_HISTORY
GROUP BY FEATURE_ID, SNAPSHOT_DATE, PROGRAM_INCREMENT;
