SELECT
    FEATURE_ID,
    PROGRAM_INCREMENT,
    SUM(STORY_POINTS) AS TOTAL_ESTIMATE,
    SUM(CASE WHEN STATUS = 'Done' THEN STORY_POINTS ELSE 0 END) AS DONE_ESTIMATE,
    SUM(STORY_POINTS)
    - SUM(CASE WHEN STATUS = 'Done' THEN STORY_POINTS ELSE 0 END)
    AS OPEN_ESTIMATE,
    COUNT(*) AS SPRINT_COUNT
FROM AMMM_JIRA_AGILE_SUMMARY
GROUP BY FEATURE_ID, PROGRAM_INCREMENT;
