WITH
Epics AS (
    SELECT
        SNAPSHOT_DATE,
        ISSUE_KEY AS EPIC_KEY,
        PARENT_KEY AS EPIC_PARENT,
        SUMMARY AS EPIC_SUMMARY,
        ESTIMATE AS EPIC_ESTIMATE,
        OPEN_ESTIMATE AS EPIC_OPEN_ESTIMATE,
    FROM AMMM_JIRA_EPIC_HISTORY
    WHERE ISSUE_TYPE = 'Epic'
),
Features As (
    SELECT
        SNAPSHOT_DATE,
        ISSUE_KEY AS FEATURE_KEY,
        PARENT_KEY AS FEATURE_PARENT,
        SUMMARY AS FEATURE_SUMMARY,
        ESTIMATE AS FEATURE_ESTIMATE,
        OPEN_ESTIMATE AS FEATURE_OPEN_ESTIMATE,
        SWAG AS FEATURE_SWAG,
        PROGRAM_PRIORITY AS BV,
        FIX_VERSION AS FEATURE_FIX_VERSION
    FROM AMMM_JIRA_EPIC_HISTORY
    WHERE ISSUE_TYPE = 'Feature'
),
SubCapabilities AS (
    SELECT
        SNAPSHOT_DATE,
        ISSUE_KEY AS SUBCAPABILITY_KEY,
        PARENT_KEY AS SUBCAPABILITY_PARENT,
    FROM AMMM_JIRA_EPIC_HISTORY
    WHERE ISSUE_TYPE = 'Sub-Capability'
),
CustomerCapabilities AS (
    SELECT
        SNAPSHOT_DATE,
        ISSUE_KEY AS CUSTCAP_KEY,
        PARENT_KEY AS CUSTCAP_PARENT,
    FROM AMMM_JIRA_EPIC_HISTORY
    WHERE ISSUE_TYPE = 'Customer Capability'
),
CustomerEpics AS (
    SELECT
        SNAPSHOT_DATE,
        ISSUE_KEY AS CUSTEPIC_KEY,
        SUMMARY AS PROGRAM,
        ESTIMATE AS CUSTCAP_ESTIMATE,
    FROM AMMM_JIRA_EPIC_HISTORY
    WHERE ISSUE_TYPE = 'Customer Epic'
)
SELECT
    EP.SNAPSHOT_DATE,
    CE.PROGRAM,
    CE.CUSTEPIC_KEY,
    CE.CUSTCAP_ESTIMATE,
    CC.CUSTCAP_KEY,
    SCT.SUBCAPABILITY_KEY,
    FT.FEATURE_KEY,
    FT.FEATURE_SUMMARY,
    FT.FEATURE_ESTIMATE,
    FT.FEATURE_OPEN_ESTIMATE,
    FT.FEATURE_SWAG,
    FT.BV,
    FT.FEATURE_FIX_VERSION,
    EP.EPIC_KEY,
    EP.EPIC_SUMMARY,
    EP.EPIC_ESTIMATE,
    EP.EPIC_OPEN_ESTIMATE
FROM Epics EP
    LEFT JOIN Features FT
        ON FT.FEATURE_KEY = EP.EPIC_PARENT
        AND FT.SNAPSHOT_DATE = EP.SNAPSHOT_DATE
    LEFT JOIN SubCapabilities SCT
        ON SCT.SUBCAPABILITY_KEY = FT.FEATURE_PARENT
        AND SCT.SNAPSHOT_DATE = FT.SNAPSHOT_DATE
    LEFT JOIN CustomerCapabilities CC
        ON CC.CUSTCAP_KEY = SCT.SUBCAPABILITY_PARENT
        AND CC.SNAPSHOT_DATE = SCT.SNAPSHOT_DATE
    LEFT JOIN CustomerEpics CE
        ON CE.CUSTEPIC_KEY = CC.CUSTCAP_PARENT
        AND CE.SNAPSHOT_DATE = CC.SNAPSHOT_DATE;
