SELECT
    OPEN_ESTIMATE AS FEATURE_OPEN_POINTS,
    ESTIMATE AS FEATURE_TOTAL_POINTS,
    TEAM_NAME AS FEATURE_TEAM,
    ISSUE_KEY AS FEATURE_ID,
    PROGRAM_INCREMENT AS FEATURE_PI,
    FIX_VERSION AS FEATURE_FIX_VERSION,
    STATUS AS FEATURE_STATUS,
    NULL AS SNAPSHOT_DATE,
    TARGET_START AS TARGET_START,
    TARGET_END AS TARGET_END,
    LAST_UPDATED AS IMET_SUMMARY_LAST_UPDATED,
    PROGRAM_PRIORITY AS BV,
    SWAG AS SWAG,
    RESOLVED AS ACTUAL_END_DATE
FROM AMMM_JIRA_EPIC_SUMMARY
WHERE ISSUE_TYPE = 'Feature'
UNION ALL
SELECT
    OPEN_ESTIMATE AS FEATURE_OPEN_POINTS,
    ESTIMATE AS FEATURE_TOTAL_POINTS,
    TEAM_NAME AS FEATURE_TEAM,
    ISSUE_KEY AS FEATURE_ID,
    PROGRAM_INCREMENT AS FEATURE_PI,
    FIX_VERSION AS FEATURE_FIX_VERSION,
    STATUS AS FEATURE_STATUS,
    SNAPSHOT_DATE,
    TARGET_START AS TARGET_START,
    TARGET_END AS TARGET_END,
    NULL AS IMET_SUMMARY_LAST_UPDATED,
    PROGRAM_PRIORITY AS BV,
    SWAG AS SWAG,
    NULL AS ACTUAL_END_DATE
FROM AMMM_JIRA_EPIC_HISTORY
WHERE ISSUE_TYPE = 'Feature'